apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "cloud-native-sl-bucket"
  annotations:
    github.com/project-slug: rav94/cloud-object-store-provisioner # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  title: 'Infra Automation for multi cloud storage bucket creation' # you can give any title
  description: An example of multi cloud storage bucket creation. # Change Description accordingly
spec:
  type: service
  owner: user:guest
  lifecycle: experimental